services:
  - name: backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 8000

  - name: frontend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: PORT
        value: 8501
